# Generated by Django 3.0.7 on 2020-10-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('found', 'Selling'), ('lost', 'Buying')], default='found', max_length=255),
        ),
    ]
