# Generated by Django 2.2.9 on 2020-11-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
